// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: alignment.proto

package microdungeon

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Alignment is a standard alignment state.
type Alignment struct {
	Ethical              int32    `protobuf:"varint,1,opt,name=ethical,proto3" json:"ethical,omitempty"`
	Moral                int32    `protobuf:"varint,2,opt,name=moral,proto3" json:"moral,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Alignment) Reset()      { *m = Alignment{} }
func (*Alignment) ProtoMessage() {}
func (*Alignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_alignment_2473e18cac4fa150, []int{0}
}
func (m *Alignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Alignment.Unmarshal(m, b)
}
func (m *Alignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Alignment.Marshal(b, m, deterministic)
}
func (dst *Alignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Alignment.Merge(dst, src)
}
func (m *Alignment) XXX_Size() int {
	return xxx_messageInfo_Alignment.Size(m)
}
func (m *Alignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Alignment.DiscardUnknown(m)
}

var xxx_messageInfo_Alignment proto.InternalMessageInfo

func (m *Alignment) GetEthical() int32 {
	if m != nil {
		return m.Ethical
	}
	return 0
}

func (m *Alignment) GetMoral() int32 {
	if m != nil {
		return m.Moral
	}
	return 0
}

func init() {
	proto.RegisterType((*Alignment)(nil), "microdungeon.Alignment")
}

func init() { proto.RegisterFile("alignment.proto", fileDescriptor_alignment_2473e18cac4fa150) }

var fileDescriptor_alignment_2473e18cac4fa150 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xcc, 0xc9, 0x4c,
	0xcf, 0xcb, 0x4d, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc9, 0xcd, 0x4c,
	0x2e, 0xca, 0x4f, 0x29, 0xcd, 0x4b, 0x4f, 0xcd, 0xcf, 0x93, 0xd2, 0x4d, 0xcf, 0x2c, 0xc9, 0x28,
	0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0xcf, 0x4f, 0xcf, 0xd7, 0x07, 0x2b, 0x4a, 0x2a, 0x4d,
	0x03, 0xf3, 0xc0, 0x1c, 0x30, 0x0b, 0xa2, 0x59, 0xc9, 0x91, 0x8b, 0xd3, 0x11, 0x66, 0x9e, 0x90,
	0x04, 0x17, 0x7b, 0x6a, 0x49, 0x46, 0x66, 0x72, 0x62, 0x8e, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x6b,
	0x10, 0x8c, 0x2b, 0x24, 0xc2, 0xc5, 0x9a, 0x9b, 0x5f, 0x94, 0x98, 0x23, 0xc1, 0x04, 0x16, 0x87,
	0x70, 0xac, 0x58, 0x66, 0x2c, 0x90, 0x67, 0x70, 0xe2, 0x8b, 0x42, 0x71, 0x41, 0x12, 0x1b, 0xd8,
	0x64, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x80, 0x7a, 0x5f, 0xb2, 0xa9, 0x00, 0x00, 0x00,
}
